# Main Alacritty Config File

# Import other config files
import = ['~/.config/alacritty/colors.toml']

# Set Fish Shell
shell = '/bin/fish'

# Set padding
[window]
dimensions = { columns = 150, lines = 40 }
padding = { x = 5, y = 5 }
dynamic_padding = true

# Font Config
[font]
normal.family = 'Hack Nerd Font'
bold.family = 'Hack Nerd Font'
italic.family = 'Hack Nerd Font'
bold_italic.family = 'Hack Nerd Font'
size = 10

[cursor]
style = { shape = 'Beam', blinking = 'On' }
vi_mode_style = { shape = 'Block', blinking = 'On' }
blink_timeout = 0

[mouse]
hide_when_typing = true
