[colors]

[colors.primary]
background = '0x0E1416'
foreground = '0xecdcc2'

[colors.normal]
black = '0x0E1416'
red = '0xa54242'
green = '0xaa562e'
yellow = '0xe6a53f'
blue = '0x3b5d82'
magenta = '0x6e4d73'
cyan = '0x5e8d87'
white = '0x5d6e80'

[colors.bright]
black = '0x2d3541'
red = '0xca5151'
green = '0xd67446'
yellow = '0xe6ae56'
blue = '0x5485b9'
magenta = '0x8d6293'
cyan = '0x8abeb7'
white = '0xecdcc2'

